name: Dependabot auto-merge

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Auto-merge Dependabot PR
        uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
