version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # or daily
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
